---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dp
  labels:
    type: db
    author: mafike
spec:
  replicas: 3
  selector:
    matchLabels:
      name: postgres-dp
  template:
    metadata:
      name: postgres-pod
      labels:
        type: postgres-dp
        author: mafike
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: postgres-secret
                   key: password
            - name: POSTGRES_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: POSTGRES_ROOT_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db





