---
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: my-nginx
      image: nginx
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "250mi"
          cpu: "500m"
