---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dp-service
  labels:
    type: postgres-dp
    author: mafike
spec:
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30001
  type: LoadBalancer
  selector:
    postgres-dp